### ISSUE TITLE
How to generate the latest database？

### ISSUE THREAD

**Issue by zhangwenda0518** [carnegie/E2P2#15]
I installed it according to the instructions, and it worked successfully. 
However, when I made an entry query, many changes occurred in MetaCyc. such as
![image](https://github.com/carnegie/E2P2/assets/77140740/2e98fbff-9362-4828-92ba-ff6b8b97dc1f)

I downloaded rpsd-4.2-20190307 from  https://ftp.dpb.carnegiescience.edu/rpsd/
![image](https://github.com/carnegie/E2P2/assets/77140740/b3a9e616-b837-4bb1-8d9f-0d3f1fa7fa0e)
I saw this explanation. Can you elaborate on it? Where should I get these latest documents?And I would like to ask how to generate the latest data set.

thanks ！

**Comment by bxuecarnegie** [comment]
We are currently in the process of updating RPSD. In the meantime however, unfortunately you'll might need to manually start checking EC numbers that are transfered due to metacyc and EC numbers being updated. One way to do so is download the file from Expasy (https://ftp.expasy.org/databases/enzyme/enzyme.dat) and parse the file.

**Comment by zhangwenda0518** [comment]
Thank you for your quick reply and look forward to the arrival of the latest version.
