### ISSUE TITLE
sequenceECs.txt not found

### ISSUE THREAD

**Issue by naomccan** [carnegie/E2P2#7]
Hi,

When initially attempting to run E2P2 I received the following error:

'Cannot verify BLAST+ bin folder from blastp.'

and discovered that the version of blast+ I installed after following the link provided on the readme did not include rpsblast. I therefore installed legacy blast as well, so that rpsblast is available.

Running E2P2 now produces a series of errors with rpsblast which end with the notice 'sequenceECs.txt not found':
![image](https://user-images.githubusercontent.com/8325164/93875194-741ff200-fccc-11ea-850a-6a071d934186.png)

Attempting to run the rps command alone suggests that the version of rpsblast included in my legacy blast installation does not recognise the options provided by e2p2:
![image](https://user-images.githubusercontent.com/8325164/93875346-b9dcba80-fccc-11ea-9bfb-186840242743.png)

Is there a specific version of rpsblast that needs to be installed for E2P2 to run successfully?

**Comment by bxuecarnegie** [comment]
sequenceECs.txt is generated by PRIAM and it uses the rpsblast from BLAST+ package, not the legacy version. You shouldn't need to install legacy blast as rpsblast is supposed to be included in the new BLAST+ 'bin' folder (currently "ncbi-blast-2.10.1+-x64-linux.tar.gz").
'Cannot verify BLAST+ bin folder from blastp.' is exactly the reason you're saying. The pipeline cannot find rpsblast from that bin folder.

**Comment by sandipmkale** [comment]
[log.txt](https://github.com/carnegie/E2P2/files/10278307/log.txt)

Hello I am also getting similar issue. Can you please help?

Thanks and regards

Sandip

**Comment by bxuecarnegie** [comment]
Your log file shows an entirely different issue. "java.lang.ClassNotFoundException: weka.core.Utils". Without knowing any other details it's hard for me to pin point what is causing the problem. Could be the version of Java.

**Comment by Frybank** [comment]
> 你好
> 
> 最初尝试运行 E2P2 时，我收到以下错误：
> 
> “无法验证来自 blastp 的 BLAST+ 箱文件夹。”
> 
> 并发现我按照自述文件中提供的链接安装的 blast+ 版本不包括 rpsblast。因此，我也安装了遗留的 blast，以便 rpsblast 可用。
> 
> 运行 E2P2 现在使用 rpsblast 产生一系列错误，这些错误以通知“sequenceECs.txt未找到”结尾： ![image](https://user-images.githubusercontent.com/8325164/93875194-741ff200-fccc-11ea-850a-6a071d934186.png)
> 
> 尝试单独运行 rps 命令表明我的旧版 blast 安装中包含的 rpsblast 版本无法识别 e2p2 提供的选项： ![image](https://user-images.githubusercontent.com/8325164/93875346-b9dcba80-fccc-11ea-9bfb-186840242743.png)
> 
> 是否需要安装特定版本的 rpsblast 才能成功运行 E2P2？

您好，我也遇到了此类问题，想要请教一下您是否解决了问题？

**Comment by Frybank** [comment]
> sequenceECs.txt 由 PRIAM 生成，它使用 BLAST+ 包中的 rpsblast，而不是旧版本。你不需要安装遗留的blast，因为rpsblast应该包含在新的BLAST+'bin'文件夹中（目前是“ncbi-blast-2.10.1+-x64-linux.tar.gz”）。 “无法从blastp验证BLAST+垃圾箱文件夹”正是你说的原因。管道无法从该 bin 文件夹中找到 rpsblast。

您好，请问您是如何解决了这个问题？

**Comment by Frybank** [comment]
> sequenceECs.txt 由 PRIAM 生成，它使用 BLAST+ 包中的 rpsblast，而不是旧版本。你不需要安装遗留的blast，因为rpsblast应该包含在新的BLAST+'bin'文件夹中（目前是“ncbi-blast-2.10.1+-x64-linux.tar.gz”）。 “无法从blastp验证BLAST+垃圾箱文件夹”正是你说的原因。管道无法从该 bin 文件夹中找到 rpsblast。

您好，请问您是如何解决了这个问题？

**Comment by bxuecarnegie** [comment]
Try determine the path of your blast+ executable and see if rpsblast is in the same folder. The input should also include all the way to "blastp ", not just it's folder. PRIAM would try to locate rpsblast by itself which is out of our control.

**Comment by Frybank** [comment]
> 尝试确定 blast+ 可执行文件的路径，看看 rpsblast 是否在同一个文件夹中。输入还应包括“blastp”，而不仅仅是它的文件夹。PRIAM会尝试自行定位rpsblast，这是我们无法控制的。

您好，我查看了blast+可执行文件的路径，并把bin路径写入全局PATH，我得blast+文件中包含rpsblast，blastp执行程序，python版本3.8.15，Java版本1.8.0_381, 运行命令如下：python run_pipeline.py --input output.pep.fasta  --blastp  blastp --java java --priam_search ../PRIAM_search.jar --rpsd ../blastdb/rpsd-4.2.fasta --priam_profile ../profiles   存在报错如下图

![1693901933542](https://github.com/carnegie/E2P2/assets/113606776/42cfb55f-da16-4698-a514-a34f99536863)

**Comment by Frybank** [comment]
> 尝试确定 blast+ 可执行文件的路径，看看 rpsblast 是否在同一个文件夹中。输入还应包括“blastp”，而不仅仅是它的文件夹。PRIAM会尝试自行定位rpsblast，这是我们无法控制的。

真心期待您的回复

**Comment by bxuecarnegie** [comment]
The error indicates that there is an issue with the profiles you've provided to the pipeline (PRIAM). Try redownload the files and provide its full path to the program. As mentioned before, these are errors caused by the PRIAM program, so it is hard for me to pinpoint the actual issue without knowing your full input.

**Comment by Frybank** [comment]
您好，很感激您的回复，我的所有安装都是按照官方配置步骤进行安装配置的，包括PRIAM_jar数据,对于报错信息中的.txt not found是因为这个PRIAM-jar原因还是其他原因，哪些提示的process error进程错误也是因为这个问题所导致的吗？如果有可能，不排除可能是我的蛋白质文件有问题，但是中肯的讲，我的蛋白文件是生物公司做的，如果您有别的建议，欢迎您的回复，再次感激您的回复。
------------------ 原始邮件 ------------------
发件人:                                                                                                                        "carnegie/E2P2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月5日(星期二) 下午4:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [carnegie/E2P2] sequenceECs.txt not found (#7)





 
The error indicates that there is an issue with the profiles you've provided to the pipeline (PRIAM). Try redownload the files and provide its full path to the program. As mentioned before, these are errors caused by the PRIAM program, so it is hard for me to pinpoint the actual issue without knowing your full input.

**Comment by Frybank** [comment]
我的蛋白文件fasta文件如下所示，貌似和软件要求的文件格式没有区别
&gt;Vf01g00004&nbsp; locus=Chr1:103132:109620:+
MASAVLHIMNSTLEWVTVALDVPSARAVVFGVHIGGHLFVEGLLLVVILFLLSQKSYKPPKRPLTKKEIDELCEEWVPEPLIPPITEEMQFEPPVLQSAAGPHTMINGKEVVNFASANYLGFIGHEKLLESCTSALEKYGVGSCGPRGFYGTIDVHLDCEARIAKFLGTPDSILYSYGISTMFSAIPSFCKKGDIIVVDEGVHWGIQNGLYLSRSTIVYFKHNDMESLRNTLEKITAENKRAKQIRRYIIVEAVYQNSGQIAPLDEIISLKEKFRFRVLLDESNSFGVLGRSGKGLTEYYGVPVEKIDIITAAMGHALATEGGFCTGSARVIDHQRLSSSGYVFSASLPPYLASAAITVIDVLEDNPALITKLKENIAVLWKGLSNIKGLAIASNPESPIVFLRLEKAIGSVKDDLKLLEDIADRVLKEDSVFVVVSKRSTLDKCRLPVGIKLFVSAAHSESDMLKACESLKRVSGVLLRNQN*
&gt;Vf01g00005&nbsp; locus=Chr1:114654:118989:-
MVEEMDSSTKGDSVEMFKTLHISSLDDDGDVEDEQEMPVEEDYDEDDDEQEPAWLDPINLSSGRSCVCDICGDPLQFLLQCHVFFEINMNNGSAGQRSHLEGFLFAIIGFTQVSHLDMMELTGLLSLELHFVNGVVLGKETKCVAVARRSIIAHRNTRVPHSNSSNYEATSGEIIKFASNTVCLEYEVINEKDIEFDDKMVDSNGYDSSLISWNRTDNGDIDKKCWVSFQSRIAKAPEQVLRYCRNGSAKPIWPMSSGQPSKADIPNCCYCGGPSNFEFQILPETLYYFGVKNDVDSLDWATIVVYTCGSSCEASVNYKEEFAWVQLYS*&nbsp;



------------------ 原始邮件 ------------------
发件人:                                                                                                                        "carnegie/E2P2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月5日(星期二) 下午4:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [carnegie/E2P2] sequenceECs.txt not found (#7)





 
The error indicates that there is an issue with the profiles you've provided to the pipeline (PRIAM). Try redownload the files and provide its full path to the program. As mentioned before, these are errors caused by the PRIAM program, so it is hard for me to pinpoint the actual issue without knowing your full input.

**Comment by bxuecarnegie** [comment]
I doubt the file is causing the issues. Yes, those error messages point to PRIAM. The error is saying that it's generating the priam profile which shouldn't be happening since the profile from our download should suffice.

**Comment by Frybank** [comment]
十分感谢您的指导，我已经通过您的细心指导解决了这个问题


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "carnegie/E2P2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月6日(星期三) 凌晨4:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [carnegie/E2P2] sequenceECs.txt not found (#7)





 
I doubt the file is causing the issues. Yes, those error messages point to PRIAM. The error is saying that it's generating the priam profile which shouldn't be happening since the profile from our download should suffice.

**Comment by Frybank** [comment]
Dear development team


&nbsp; &nbsp; &nbsp;I have configured and installed PlantClusterFinder version 1.3 according to the requirements, and successfully run the test data, but when I run my own data, the gtpf file shows an error. According to the requirements of the file, The gtpf.txt file is composed of gene_id, transcript_id and protein_id, but transcript_id and protein_id are the same data. I don't understand much about this, because I have obtained the file in the format of gff3, as shown below. It should be the same as gene_id and transcript_id
&nbsp; &nbsp; &nbsp;Sincerely looking forward to your reply


GFFfile

Here are the glof files and gtpf files I made according to the software instructions, as well as the protein sequence data files


glof.txt



&nbsp;
gtpf.txt


pep.fasta

**Comment by bxuecarnegie** [comment]
This issue is unrelated to E2P2, please set up a ticket in the correct repository.

> Dear development team &nbsp; &nbsp; &nbsp;I have configured and installed PlantClusterFinder version 1.3 according to the requirements, and successfully run the test data, but when I run my own data, the gtpf file shows an error. According to the requirements of the file, The gtpf.txt file is composed of gene_id, transcript_id and protein_id, but transcript_id and protein_id are the same data. I don't understand much about this, because I have obtained the file in the format of gff3, as shown below. It should be the same as gene_id and transcript_id &nbsp; &nbsp; &nbsp;Sincerely looking forward to your reply GFFfile Here are the glof files and gtpf files I made according to the software instructions, as well as the protein sequence data files glof.txt &nbsp; gtpf.txt pep.fasta
